services:
  test:
    build: .
    environment:
      CI: "1"
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./allure-results:/app/allure-results
      - ./test-results:/app/test-results
